### ISSUE TITLE
Demo doesn't work in iPhone

### ISSUE THREAD

**Issue by tomByrer** [mike-zarandona/StickyStack.js#3]
If it is mobile friendly & Codepen is the issue, then try gh-pages?

**Comment by mike-zarandona** [comment]
The culprit here is in fact CodePen - if you're testing a pen on mobile you can use their built in `debug` mode to view without CodePen getting in the way.  E.g., [this link](http://s.codepen.io/mike-zarandona/debug/Dasnw) will work on mobile.

Thanks for the heads up, I'll update the docs at some point in the future.
